### ISSUE TITLE
Segmentation fault caused by extremely short alignments from a small, circular genome

### ISSUE THREAD

**Issue by gringer** [jts/nanopolish#267]
Nanopolish is giving me a challenge again. I'm trying to polish up a circular plasmid sequence (mapped in a circular fashion with GraphMap), but something in the alignment is causing problems for nanopolish.

Here's the GDB backtrace:

```
Program received signal SIGSEGV, Segmentation fault.                                                                                                       EventAlignmentRecord::EventAlignmentRecord (this=0x555560161b58, sr=<optimized out>, strand_idx=<optimized out>, seq_record=...)
    at src/alignment/nanopolish_alignment_db.cpp:80
80          this->stride = this->aligned_events.front().read_pos < this->aligned_events.back().read_pos ? 1 : -1;
(gdb) bt
#0  EventAlignmentRecord::EventAlignmentRecord (this=0x555560161b58, sr=<optimized out>, strand_idx=<optimized out>, seq_record=...)
    at src/alignment/nanopolish_alignment_db.cpp:80
#1  0x00005555556290f4 in __gnu_cxx::new_allocator<EventAlignmentRecord>::construct<EventAlignmentRecord, SquiggleRead*&, unsigned long&, SequenceAlignmentRecord const&> (this=0x7fffffffc690, __p=<optimized out>) at /usr/include/c++/6/ext/new_allocator.h:120
#2  std::allocator_traits<std::allocator<EventAlignmentRecord> >::construct<EventAlignmentRecord, SquiggleRead*&, unsigned long&, SequenceAlignmentRecord const&> (__a=..., __p=<optimized out>) at /usr/include/c++/6/bits/alloc_traits.h:475
#3  std::vector<EventAlignmentRecord, std::allocator<EventAlignmentRecord> >::emplace_back<SquiggleRead*&, unsigned long&, SequenceAlignmentRecord const&>
    (this=0x7fffffffc690) at /usr/include/c++/6/bits/vector.tcc:96
#4  AlignmentDB::_load_events_by_region_from_read (this=this@entry=0x7fffffffce90, sequence_records=std::vector of length 1293, capacity 2048 = {...})
    at src/alignment/nanopolish_alignment_db.cpp:568
#5  0x0000555555629beb in AlignmentDB::load_region (this=this@entry=0x7fffffffce90, contig="tig00000001_contig", start_position=start_position@entry=0, 
    stop_position=stop_position@entry=5825) at src/alignment/nanopolish_alignment_db.cpp:392
#6  0x00005555555fb45f in call_variants_for_region (contig="tig00000001_contig", region_start=40, region_end=5785, 
    out_fp=out_fp@entry=0x7ffff6ac7600 <_IO_2_1_stdout_>) at src/nanopolish_call_variants.cpp:876
#7  0x00005555555fe072 in call_variants_main (argc=<optimized out>, argv=<optimized out>) at src/nanopolish_call_variants.cpp:1174
#8  0x0000555555565395 in std::function<int (int, char**)>::operator()(int, char**) const (__args#1=<optimized out>, __args#0=<optimized out>, 
    this=0x555555e0efb0) at /usr/include/c++/6/functional:2127
#9  main (argc=14, argv=0x7fffffffd788) at src/main/nanopolish.cpp:74

```

* Removing unmapped reads from the BAM file doesn't get rid of the segfault.
* Removing secondary reads also doesn't get rid of the segfault.

However, removing reads with an alignment score below 100 *did* deal to the segfault. I'm going to guess from this that nanopolish struggles a bit with circular genomes, and can't handle alignments where the alignment length is below some particular length (e.g. <20bp).

**Comment by jts** [comment]
Hi David,

Can you provide some data to reproduce the problem?

Thanks,
Jared

**Comment by jts** [comment]
The underlying assertion is now fixed. I still recommend filtering very short alignments out.
