### ISSUE TITLE
Problem with merge

### ISSUE THREAD

**Issue by SashaMeow** [jts/nanopolish#291]
I sucessfully ran nanopolish_makerange.py and now trying to merge it in one polished genome by running nanopolish_merge.py. 
However when I start merging I get an error: 
```
...
Insert tig00060257 99960
Insert tig00060257 49960
Merging tig00000001 0
Merging tig00000001 49960
Traceback (most recent call last):
  File "/Users/katjasch/nanopolish/scripts/nanopolish_merge.py", line 93, in <module>
    assembly = merge_into_consensus(assembly, sequence, OVERLAP_LENGTH)
  File "/Users/katjasch/nanopolish/scripts/nanopolish_merge.py", line 28, in merge_into_consensus
    for i in xrange(0, len(aln_con) / 2):
NameError: name 'xrange' is not defined
```
I went back an look at the files that were created by nanopolish_makerange.py and it's kind of looks a little off to me because the regions are overlapping. 
example:
```
polished.tig00000001:0-50200.fa
polished.tig00000001:100000-150200.fa
polished.tig00000001:1000000-1050200.fa
polished.tig00000001:1050000-1100200.fa
polished.tig00000001:1100000-1150200.fa
polished.tig00000001:1150000-1200200.fa
polished.tig00000001:1200000-1250200.fa
polished.tig00000001:1250000-1300200.fa
polished.tig00000001:1300000-1350200.fa
polished.tig00000001:1350000-1400200.fa
polished.tig00000001:1400000-1450200.f
polished.tig00000001:1450000-1471432.fa
polished.tig00000001:150000-200200.fa
polished.tig00000001:200000-250200.fa
polished.tig00000001:250000-300200.fa
polished.tig00000001:300000-350200.fa
polished.tig00000001:350000-400200.fa
polished.tig00000001:400000-450200.fa
polished.tig00000001:450000-500200.fa
polished.tig00000001:50000-100200.fa
polished.tig00000001:500000-550200.fa
polished.tig00000001:550000-600200.fa
polished.tig00000001:600000-650200.fa
polished.tig00000001:650000-700200.fa
...
```
What should I do to resolve this issue?

**Comment by jts** [comment]
Hi @SashaMeow,

`xrange` was removed in python3 but @devindrown updated this script to use `range` instead. Could you please update to the latest nanopolish code and try again?

thanks,
Jared

**Comment by SashaMeow** [comment]
@jts 
I'm trying to update/reinstall new nanopolish, but keep run into this:
```
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
```

**Comment by jts** [comment]
try install gcc through homebrew then running:

```
make CXX=g++7 CC=gcc-7
```

(you might need to change the GCC version to whatever homebrew installs)

**Comment by SashaMeow** [comment]
I'll try that. I have gcc installed already, so I guess it need to be linked properly.

**Comment by SashaMeow** [comment]
So homebrew tells me that I have gcc 4.8 and gcc 7.2.0
I tried to ran make for nanopolish as 
```
 make CXX=g++7 CC=gcc-7
```
It sisnt work
and I tried to ran it as 
```
make CXX=g++7.2.0 CC=gcc-7.2.0
```

both did not work.
I was able to install the nanopolish once, so I wonder how come now I can't

**Comment by jts** [comment]
sorry I made a typo. Try:

```
make CXX=g++-7 CC=gcc-7
```

or

```
make CXX=g++-4.8 CC=gcc-4.8
```

**Comment by SashaMeow** [comment]
@jts 

Alright! thank you it worked. I was able to finish installation process and ran nanopolish_merge.py

**Comment by jts** [comment]
great!
