### ISSUE TITLE
KeyError num_motifs when calculating methylation frequency

### ISSUE THREAD

**Issue by avilella** [jts/nanopolish#586]
Hi all,

I tried running the calculate frequency script on a results file produced by f5c from @hasindu2008 

I get an error that I can't seem to solve:

```
albert_vilella_cegx_co_uk@avilella-ubuntu1604-f5c:~$ ~/csvtk headers -t f5c.result.tsv 
# f5c.result.tsv
1       chromosome
2       start
3       end
4       read_name
5       log_lik_ratio
6       log_lik_methylated
7       log_lik_unmethylated
8       num_calling_strands
9       num_cpgs
10      sequence
albert_vilella_cegx_co_uk@avilella-ubuntu1604-f5c:~$ ~/csvtk stats -t f5c.result.tsv 
file             num_cols   num_rows
f5c.result.tsv         10    101,384
albert_vilella_cegx_co_uk@avilella-ubuntu1604-f5c:~$ python ~/nanopolish-0.11.1/scripts/calculate_methylation_frequency.py -i f5c.result.tsv
Traceback (most recent call last):
  File "/home/albert_vilella_cegx_co_uk/nanopolish-0.11.1/scripts/calculate_methylation_frequency.py", line 43, in <module>
    num_sites = int(record['num_motifs']) 
KeyError: 'num_motifs'
```
Any ideas?

**Comment by avilella** [comment]
```
albert_vilella_cegx_co_uk@avilella-ubuntu1604-f5c:~$ head f5c.result.tsv 
chromosome      start   end     read_name       log_lik_ratio   log_lik_methylated      log_lik_unmethylated    num_calling_strands     num_cpgs        sequence
m13r_t7p_de_bruijn_v1   25      25      751e17b1-0e46-445b-acb2-cd0a82535ba5    4.90    -156.35 -161.24 1       1       GATTACGCCAA
m13r_t7p_de_bruijn_v1   40      46      751e17b1-0e46-445b-acb2-cd0a82535ba5    5.28    -115.99 -121.27 1       2       GGTACCGAGCTCGGATC
m13r_t7p_de_bruijn_v1   61      65      751e17b1-0e46-445b-acb2-cd0a82535ba5    4.20    -176.37 -180.57 1       2       AGTAACGGCCGCCAG
m13r_t7p_de_bruijn_v1   83      83      751e17b1-0e46-445b-acb2-cd0a82535ba5    8.09    -114.18 -122.27 1       1       GAATTCGGCTT
m13r_t7p_de_bruijn_v1   105     116     751e17b1-0e46-445b-acb2-cd0a82535ba5    11.29   -173.75 -185.04 1       3       CTACACGACGCTCTTCCGATCT
m13r_t7p_de_bruijn_v1   171     171     751e17b1-0e46-445b-acb2-cd0a82535ba5    3.54    -113.46 -117.00 1       1       TCAAACGAAAC
m13r_t7p_de_bruijn_v1   231     231     751e17b1-0e46-445b-acb2-cd0a82535ba5    5.84    -115.90 -121.74 1       1       TCAAGCGAAGC
m13r_t7p_de_bruijn_v1   291     291     751e17b1-0e46-445b-acb2-cd0a82535ba5    4.36    -120.26 -124.62 1       1       TCAATCGAATC
m13r_t7p_de_bruijn_v1   320     330     751e17b1-0e46-445b-acb2-cd0a82535ba5    26.34   -171.06 -197.39 1       3       CACAACGGAACGTAACGCAAC
albert_vilella_cegx_co_uk@avilella-ubuntu1604-f5c:~$ 
```

**Comment by avilella** [comment]
I get the same error with the example chr22 result file from the f5c doc:

```
python ~/nanopolish-0.11.1/scripts/calculate_methylation_frequency.py -i chr22_meth_example/result.tsv 
Traceback (most recent call last):
  File "/home/albert_vilella_cegx_co_uk/nanopolish-0.11.1/scripts/calculate_methylation_frequency.py", line 43, in <module>
    num_sites = int(record['num_motifs']) 
KeyError: 'num_motifs'
```

**Comment by jts** [comment]
We changed the name of that column in the output since `call-methylation` can now call at more than CpG sites.

**Comment by colindaven** [comment]
Just had this error in reverse as I am recalling using an older version of albacore/nanopore etc to produce comparable results with older data.  Anyway, if it wasn't obvious from jts 's answer the following changes to the 
`calculate_methylation_frequency.py`    should solve it (maybe vice versa in your case):

```
   #num_sites = int(record['num_cpgs']) 
    num_sites = int(record['num_motifs']) 
```

**Comment by jts** [comment]
Thanks @colindaven
